
global:
  external_labels:
    app: litmuschaos
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - "/etc/prometheus-rules/*.rules"
scrape_configs:
  - job_name: 'chaos-monitor'
    static_configs:
      - targets: ['chaos-monitor.litmus.svc.cluster.local:8080']

# Added a new scrape config for the NodeExporter
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter.litmus.svc.cluster.local:9100']

# Added a new alert rule for the NodeExporter
alerts:
  - alert: NodeExporterDown
    expr: absent(up{job="node-exporter"})
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Node Exporter down
      description: Node Exporter has been down for 5 minutes.
