name: Release
on:
  create:
    tags:
      - '**'

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      # Install golang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.20.0

      # Checkout to the latest commit
      # On specific directory/path
      - name: Checkout
        uses: actions/checkout@v2

  image-build:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:
      # Checkout to the latest commit
      # On specific directory/path
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: login to GitHub Container Registry
        run: echo ${{ secrets.DPASS }} | docker login -u ${{ secrets.DNAME }} --password-stdin

      - name: Set Tag
        run: |
          TAG="${GITHUB_REF#refs/*/}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${TAG}" >> $GITHUB_ENV

      - name: Build & Push Docker Image with version tag
        env:
          DOCKER_REPO: litmuschaos
          DOCKER_IMAGE: chaos-exporter
          DOCKER_TAG: ${RELEASE_TAG}
          DNAME: ${{ secrets.DNAME }}
          DPASS: ${{ secrets.DPASS }}
        run: |
          make push

      - name: Build & Push Docker Image with latest tag
        env:
          DOCKER_REPO: litmuschaos
          DOCKER_IMAGE: chaos-exporter
          DOCKER_TAG: latest
          DNAME: ${{ secrets.DNAME }}
          DPASS: ${{ secrets.DPASS }}
        run: |
          make push
