---
# This workflow is to perform automatic release on litmus-ansible repository
# Please provide the release version and release tag in github secrets for the upcoming release.
name: AutoRelease

# Executes a job at 10:15am on the 15th day of every month
on:
    schedule:
    - cron:  '0 15 10 15 * *'

jobs:
    release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:

        # create a release branch from master
        # Provide release branch from the github secret ex. 1.9.x
        - uses: peterjgrainger/action-create-branch@v1.0.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            branch: '${{ secrets.RELEASE_BRANCH }}'
  
        # Provide release tag from the github secret ex. 1.9.0
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "${{ secrets.RELEASE_TAG }}"
            prerelease: false
            title: "${{ secrets.RELEASE_TAG }}"
