---
# This workflow is to perform automatic release on chaos-exporter repository
name: AutoRelease

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tag:
        description: 'Release tag'
        required: true
      branch:
        description: 'Release branch name'


jobs:
    release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
        # create a release branch from master
      - uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{ github.event.inputs.branch }}'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.tag }}"
          prerelease: false
          title: "${{ github.event.inputs.tag }}"